classifier size: 11
max switch rule count: 11
average switch rule count: 11
print : match: ('vlan_pcp', 0) ('vlan_id', 2)
  -> set([Controller])
 match: ('vlan_pcp', 0) ('vlan_id', 3)
  -> set([Controller])
 match: ('vlan_pcp', 0) ('vlan_id', 4)
  -> set([Controller])
 match: ('vlan_pcp', 0) ('vlan_id', 5)
  -> set([Controller])
 match: ('vlan_pcp', 0) ('vlan_id', 6)
  -> set([Controller])
 match: ('vlan_pcp', 0) ('vlan_id', 7)
  -> set([Controller])
 match: ('vlan_pcp', 0) ('vlan_id', 8)
  -> set([Controller])
 match: ('vlan_pcp', 0) ('vlan_id', 9)
  -> set([Controller])
 match: ('vlan_pcp', 0) ('vlan_id', 10)
  -> set([Controller])
 match: ('vlan_pcp', 0) ('vlan_id', 11)
  -> set([Controller])
 identity
  -> set([]) 
---------------------------------
